FROM node:19.5.0-alpine AS build

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ENV NPM_CONFIG_COLOR=false

COPY . .
RUN npm install

RUN npm run build

FROM node:19.5.0-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY --from=build /usr/src/app/package.json ./package.json
COPY --from=build /usr/src/app/package-lock.json ./package-lock.json
COPY --from=build /usr/src/app/build build/
RUN npm install --omit=dev

ENV PORT=80
EXPOSE 80
CMD ["npm", "run", "prod"]
