name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      # - name: Build site
      #   run: npm run build 
      # doesnt work anymore (static adapter needs the backend running to grab info while building)

      - name: Sync SvelteKit
        run: npx svelte-kit sync #to make the  necessary .svelte-kit folder

      - name: Test
        run: CI=true npm run test

  lint:
    runs-on: ubuntu-latest
    name: Lint

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      # - name: Build site
      #   run: npm run build 
      # doesnt work anymore (static adapter needs the backend running to grab info while building)

      - name: Sync SvelteKit
        run: npx svelte-kit sync #to make the  necessary .svelte-kit folder

      - name: Lint Code
        run: npm run lint
